import { StyleSheet } from 'react-native';

import { colors } from '@/theme/colors';
import { radius, spacing } from '@/theme/spacing';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  loader: { flex: 1, marginTop: 40 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  gallery: { backgroundColor: colors.bgSubtle },
  galleryWrap: { position: 'relative' },
  galleryPlaceholder: {
    backgroundColor: colors.bgSubtle,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  galleryCounter: {
    position: 'absolute',
    right: spacing.md,
    top: spacing.md,
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: radius.sm,
    zIndex: 5,
  },
  galleryCounterText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '600',
  },
  content: { padding: spacing.lg, gap: 6 },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  price: { fontSize: 22, fontWeight: '700', color: colors.text },
  title: { fontSize: 17, fontWeight: '600', color: colors.text },
  categoryLink: { fontSize: 13, color: colors.primary, fontWeight: '600', marginTop: 2 },
  meta: { fontSize: 13, color: colors.muted, marginBottom: spacing.sm },
  contacts: {
    gap: spacing.sm,
    marginBottom: spacing.md,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: colors.border,
  },
  contactsTitle: { fontSize: 14, fontWeight: '700', color: colors.text, marginBottom: spacing.xs },
  contactBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: 12,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.bg,
  },
  contactBtnPrimary: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  contactIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.bgSubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contactIconWrapOnPrimary: { backgroundColor: 'rgba(255,255,255,0.2)' },
  contactBody: { flex: 1, gap: 2 },
  contactLabel: { fontSize: 14, fontWeight: '600', color: colors.text },
  contactLabelOnPrimary: { color: colors.white },
  contactHint: { fontSize: 12, color: colors.muted },
  contactHintOnPrimary: { color: 'rgba(255,255,255,0.8)' },
  sellerCard: {
    marginBottom: spacing.md,
    gap: spacing.sm,
    paddingBottom: spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  sellerMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  sellerAvatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.bgSubtle },
  sellerAvatarPh: { alignItems: 'center', justifyContent: 'center' },
  sellerText: { flex: 1, gap: 4 },
  sellerName: { fontSize: 15, fontWeight: '600', color: colors.text },
  sellerType: { fontSize: 13, color: colors.muted },
  subscribeBtn: {
    alignSelf: 'stretch',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: 10,
    alignItems: 'center',
  },
  subscribeBtnOn: {
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.primary,
  },
  subscribeText: { color: colors.white, fontWeight: '700', fontSize: 14 },
  subscribeTextOn: { color: colors.primary },
  reportLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'flex-start',
    marginBottom: spacing.md,
  },
  reportLinkText: { color: colors.error, fontWeight: '600', fontSize: 13 },
  headerReport: { paddingHorizontal: 8 },
  sectionTitle: { fontSize: 15, fontWeight: '700', marginBottom: 4, color: colors.text },
  description: { fontSize: 14, lineHeight: 20, color: colors.text, marginBottom: spacing.sm },
});
