import { StyleSheet } from 'react-native';

import { colors } from '@/theme/colors';
import { radius, spacing } from '@/theme/spacing';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bgSubtle },
  content: { padding: spacing.lg, gap: spacing.md, paddingBottom: 40 },
  hero: {
    backgroundColor: colors.bg,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  heroTitle: { fontSize: 20, fontWeight: '700', color: colors.text },
  heroText: { fontSize: 14, lineHeight: 21, color: colors.textSecondary },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(4, 73, 45, 0.12)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radius.sm,
  },
  badgeText: { color: colors.primary, fontWeight: '700', fontSize: 12 },
  card: {
    backgroundColor: colors.bg,
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.md,
  },
  label: { fontSize: 13, fontWeight: '600', color: colors.textSecondary, marginBottom: 6 },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.text,
    backgroundColor: colors.bg,
  },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.bgMuted,
  },
  chipOn: { borderColor: colors.primary, backgroundColor: 'rgba(4, 73, 45, 0.08)' },
  chipText: { color: colors.text, fontSize: 13, fontWeight: '600' },
  chipTextOn: { color: colors.primary },
  fileBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: 'dashed',
    borderRadius: radius.md,
    padding: 14,
    gap: 4,
  },
  fileBtnOn: { borderColor: colors.primary, borderStyle: 'solid' },
  fileTitle: { fontWeight: '700', color: colors.text },
  fileHint: { fontSize: 12, color: colors.muted },
  checkRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  checkText: { flex: 1, fontSize: 13, lineHeight: 19, color: colors.textSecondary },
  error: { color: colors.error, fontSize: 13 },
  successBox: {
    backgroundColor: 'rgba(4, 73, 45, 0.1)',
    borderRadius: radius.lg,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  successTitle: { fontWeight: '700', color: colors.primary, fontSize: 16 },
  successText: { color: colors.textSecondary, lineHeight: 20 },
  submit: {
    backgroundColor: colors.primary,
    borderRadius: radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
  },
  submitDisabled: { opacity: 0.6 },
  submitText: { color: colors.white, fontWeight: '700', fontSize: 15 },
  benefit: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' },
  benefitText: { flex: 1, fontSize: 14, color: colors.text, lineHeight: 20 },
});
