export const JOB_PROFESSIONS = [
  { value: 'administrator', popular: true, ru: 'Администратор', uz: 'Administrator' },
  { value: 'laborer', popular: true, ru: 'Разнорабочий', uz: 'Turli ishchi' },
  { value: 'courier', popular: true, ru: 'Курьер', uz: 'Kuryer' },
  { value: 'packer', popular: true, ru: 'Упаковщик', uz: 'Qadoqlovchi' },
  { value: 'truck_driver', popular: true, ru: 'Водитель грузового транспорта', uz: 'Yuk mashinasi haydovchisi' },
  { value: 'driver_expeditor', popular: true, ru: 'Водитель-экспедитор', uz: 'Haydovchi-ekspeditor' },
  { value: 'guard', popular: true, ru: 'Охранник', uz: "Qo'riqchi" },
  { value: 'call_center', popular: false, ru: 'Оператор колл-центра', uz: 'Call-markaz operatori' },
  { value: 'smm', popular: false, ru: 'SMM-специалист', uz: 'SMM-mutaxassis' },
  { value: 'emergency_comissar', popular: false, ru: 'Аварийный комиссар', uz: 'Avariya komissari' },
  { value: 'avitologist', popular: false, ru: 'Авитолог', uz: 'Avitolog' },
  { value: 'auto_tinsmith', popular: false, ru: 'Автожестянщик', uz: 'Avtoqalaychi' },
  { value: 'driving_instructor', popular: false, ru: 'Автоинструктор', uz: 'Avtoinstruktor' },
  { value: 'auto_painter', popular: false, ru: 'Автомаляр', uz: 'Avtobopoyachi' },
  { value: 'auto_mechanic', popular: false, ru: 'Автомеханик', uz: 'Avtomexanik' },
  { value: 'accountant', popular: false, ru: 'Бухгалтер', uz: 'Buxgalter' },
  { value: 'sales', popular: false, ru: 'Продавец', uz: 'Sotuvchi' },
  { value: 'manager', popular: false, ru: 'Менеджер', uz: 'Menejer' },
  { value: 'waiter', popular: false, ru: 'Официант', uz: 'Ofitsiant' },
  { value: 'cook', popular: false, ru: 'Повар', uz: 'Oshpaz' },
  { value: 'cleaner', popular: false, ru: 'Уборщик', uz: 'Tozalovchi' },
  { value: 'loader', popular: false, ru: 'Грузчик', uz: 'Yuk tashuvchi' },
  { value: 'electrician', popular: false, ru: 'Электрик', uz: 'Elektrik' },
  { value: 'plumber', popular: false, ru: 'Сантехник', uz: 'Santexnik' },
  { value: 'welder', popular: false, ru: 'Сварщик', uz: 'Payvandchi' },
  { value: 'builder', popular: false, ru: 'Строитель', uz: 'Quruvchi' },
  { value: 'nurse', popular: false, ru: 'Медсестра', uz: 'Hamshira' },
  { value: 'doctor', popular: false, ru: 'Врач', uz: 'Shifokor' },
  { value: 'teacher', popular: false, ru: 'Учитель', uz: "O'qituvchi" },
  { value: 'lawyer', popular: false, ru: 'Юрист', uz: 'Yurist' },
  { value: 'hr', popular: false, ru: 'HR-специалист', uz: 'HR-mutaxassis' },
  { value: 'developer', popular: false, ru: 'Программист', uz: 'Dasturchi' },
  { value: 'designer', popular: false, ru: 'Дизайнер', uz: 'Dizayner' },
  { value: 'web_designer', popular: false, ru: 'Веб-дизайнер', uz: 'Veb-dizayner' },
  { value: 'veterinarian', popular: false, ru: 'Ветеринар', uz: 'Veterinar' },
  { value: 'vet_assistant', popular: false, ru: 'Ветеринарный санитар', uz: 'Veterinar sanitari' },
  { value: 'video_editor', popular: false, ru: 'Видеомонтажёр', uz: 'Video montajchi' },
  { value: 'cameraman', popular: false, ru: 'Видеооператор', uz: 'Videooperator' },
  { value: 'event_host', popular: false, ru: 'Ведущий мероприятий', uz: 'Tadbir boshlovchisi' },
  { value: 'cashier', popular: false, ru: 'Кассир', uz: 'Kassir' },
  { value: 'secretary', popular: false, ru: 'Секретарь', uz: 'Kotib' },
  { value: 'driver', popular: false, ru: 'Водитель', uz: 'Haydovchi' },
  { value: 'taxi_driver', popular: false, ru: 'Водитель такси', uz: 'Taksi haydovchisi' },
  { value: 'storekeeper', popular: false, ru: 'Кладовщик', uz: 'Omborchi' },
  { value: 'consultant', popular: false, ru: 'Консультант', uz: 'Maslahatchi' },
  { value: 'marketer', popular: false, ru: 'Маркетолог', uz: 'Marketolog' },
  { value: 'locksmith', popular: false, ru: 'Слесарь', uz: 'Chilangar' },
  { value: 'painter', popular: false, ru: 'Маляр', uz: "Bo'yoqchi" },
  { value: 'barber', popular: false, ru: 'Парикмахер', uz: 'Sartarosh' },
  { value: 'beautician', popular: false, ru: 'Косметолог', uz: 'Kosmetolog' },
  { value: 'security_head', popular: false, ru: 'Начальник охраны', uz: "Qo'riqlash boshlig'i" },
  { value: 'project_manager', popular: false, ru: 'Проект-менеджер', uz: 'Loyiha menejeri' },
  { value: 'analyst', popular: false, ru: 'Аналитик', uz: 'Tahlilchi' },
  { value: 'translator', popular: false, ru: 'Переводчик', uz: 'Tarjimon' },
  { value: 'pharmacist', popular: false, ru: 'Фармацевт', uz: 'Farmatsevt' },
  { value: 'engineer', popular: false, ru: 'Инженер', uz: 'Muhandis' },
  { value: 'operator', popular: false, ru: 'Оператор', uz: 'Operator' },
  { value: 'packer_warehouse', popular: false, ru: 'Комплектовщик', uz: 'Komplektlovchi' },
  { value: 'merchandiser', popular: false, ru: 'Мерчендайзер', uz: 'Merchendayzer' },
  { value: 'promoter', popular: false, ru: 'Промоутер', uz: 'Promouter' },
  { value: 'nanny', popular: false, ru: 'Няня', uz: 'Enaga' },
  { value: 'caretaker', popular: false, ru: 'Сиделка', uz: 'Qarovchi' },
]

export const JOB_INDUSTRY_SEEK = [
  { value: 'JobSeek_architecture', ru: 'Архитектура и дизайн', uz: 'Arxitektura va dizayn' },
  { value: 'JobSeek_banking', ru: 'Банковские и финансовые услуги', uz: 'Bank va moliyaviy xizmatlar' },
  { value: 'JobSeek_personal_services', ru: 'Бытовые и персональные услуги', uz: 'Maishiy va shaxsiy xizmatlar' },
  { value: 'JobSeek_gov', ru: 'Госслужба', uz: 'Davlat xizmati' },
  { value: 'JobSeek_hotel_tourism', ru: 'Гостиничный бизнес и туризм', uz: 'Mehmonxona biznesi va turizm' },
  { value: 'JobSeek_mining', ru: 'Добыча, переработка угля, руд и других полезных ископаемых', uz: 'Qazilmalarni qazib olish' },
  { value: 'JobSeek_oil_gas', ru: 'Добыча, переработка, транспортировка нефти и газа', uz: 'Neft va gaz' },
  { value: 'JobSeek_logistics', ru: 'Доставка, грузоперевозки и логистика', uz: 'Logistika' },
  { value: 'JobSeek_utilities', ru: 'ЖКХ и городская инфраструктура', uz: "Kommunal xo'jalik" },
  { value: 'JobSeek_gambling', ru: 'Игорный бизнес', uz: 'Qimor biznesi' },
  { value: 'JobSeek_it', ru: 'Информационные технологии', uz: 'Axborot texnologiyalari' },
  { value: 'JobSeek_arts', ru: 'Искусство и развлечения', uz: "San'at va ko'ngilochar" },
  { value: 'JobSeek_cleaning', ru: 'Клининг', uz: 'Klinning' },
  { value: 'JobSeek_consulting', ru: 'Консалтинг', uz: 'Konsalting' },
  { value: 'JobSeek_forestry', ru: 'Лесная и деревообрабатывающая промышленность', uz: "Yog'ochsozlik" },
  { value: 'JobSeek_marketing', ru: 'Маркетинг, реклама и PR', uz: 'Marketing, reklama va PR' },
  { value: 'JobSeek_medicine', ru: 'Медицина и фармацевтика', uz: 'Tibbiyot va farmatsevtika' },
  { value: 'JobSeek_metallurgy', ru: 'Металлургическая промышленность', uz: 'Metallurgiya' },
  { value: 'JobSeek_nko', ru: 'НКО и общественная деятельность', uz: 'NNT' },
  { value: 'JobSeek_defense', ru: 'Оборонная промышленность', uz: 'Mudofaa sanoati' },
  { value: 'JobSeek_education', ru: 'Образование и наука', uz: "Ta'lim va fan" },
  { value: 'JobSeek_catering', ru: 'Общественное питание', uz: 'Umumiy ovqatlanish' },
  { value: 'JobSeek_events', ru: 'Организация мероприятий', uz: 'Tadbirlar' },
  { value: 'JobSeek_security', ru: 'Охрана и общественный порядок', uz: "Qo'riqlash" },
  { value: 'JobSeek_waste', ru: 'Переработка отходов', uz: 'Chiqindilarni qayta ishlash' },
  { value: 'JobSeek_food_industry', ru: 'Пищевая промышленность', uz: 'Oziq-ovqat sanoati' },
  { value: 'JobSeek_auto_sales', ru: 'Продажа и обслуживание автомобилей', uz: 'Avtosavdo' },
  { value: 'JobSeek_realestate', ru: 'Продажа и управление недвижимостью', uz: "Ko'chmas mulk" },
  { value: 'JobSeek_consumer_goods', ru: 'Производство непродовольственных потребительских товаров', uz: "Iste'mol tovarlari" },
  { value: 'JobSeek_machinery', ru: 'Производство промышленного оборудования и станков', uz: 'Stanoklar' },
  { value: 'JobSeek_textiles', ru: 'Производство тканей, одежды и обуви', uz: "To'qimachilik" },
  { value: 'JobSeek_electro_opt', ru: 'Производство электро- и оптического оборудования', uz: 'Elektrooptika' },
  { value: 'JobSeek_electronics', ru: 'Производство электроники и бытовой техники', uz: 'Elektronika ishlab chiqarish' },
  { value: 'JobSeek_aerospace', ru: 'Ракетно-космическая промышленность', uz: 'Kosmik sanoat' },
  { value: 'JobSeek_renovation', ru: 'Ремонт и отделка помещений', uz: "Ta'mirlash" },
  { value: 'JobSeek_funeral', ru: 'Ритуальные услуги', uz: 'Ritual xizmatlar' },
  { value: 'JobSeek_trade', ru: 'Розничная и оптовая торговля', uz: 'Savdo' },
  { value: 'JobSeek_agriculture', ru: 'Сельское хозяйство', uz: "Qishloq xo'jaligi" },
  { value: 'JobSeek_warehouses', ru: 'Склады и хранилища', uz: 'Omborlar' },
  { value: 'JobSeek_media', ru: 'СМИ и издательское дело', uz: 'OAV' },
  { value: 'JobSeek_insurance', ru: 'Страхование', uz: "Sug'urta" },
  { value: 'JobSeek_build_civil', ru: 'Строительство жилых и коммерческих объектов', uz: 'Fuqarolik qurilishi' },
  { value: 'JobSeek_build_infra', ru: 'Строительство промышленных и инфраструктурных объектов', uz: 'Infratuzilma qurilishi' },
  { value: 'JobSeek_taxi', ru: 'Такси и пассажирские перевозки', uz: 'Taksi' },
  { value: 'JobSeek_telecom', ru: 'Телекоммуникации и связь', uz: 'Aloqa' },
  { value: 'JobSeek_tech_repair', ru: 'Техническое обслуживание, ремонт техники и оборудования', uz: 'Texnik xizmat' },
  { value: 'JobSeek_transport_eng', ru: 'Транспортное машиностроение', uz: 'Transport mashinasozligi' },
  { value: 'JobSeek_heavy_eng', ru: 'Тяжёлое машиностроение', uz: "Og'ir mashinasozlik" },
  { value: 'JobSeek_hr', ru: 'Управление персоналом', uz: 'Xodimlarni boshqarish' },
  { value: 'JobSeek_transport_infra', ru: 'Управление транспортной инфраструктурой', uz: 'Transport infratuzilmasi' },
  { value: 'JobSeek_fitness', ru: 'Фитнес-клубы, спа и салоны красоты', uz: "Fitnes va go'zallik" },
  { value: 'JobSeek_chemical', ru: 'Химическая промышленность', uz: 'Kimyo sanoati' },
  { value: 'JobSeek_energy', ru: 'Энергетика', uz: 'Energetika' },
  { value: 'JobSeek_legal', ru: 'Юриспруденция', uz: 'Yurisprudensiya' },
]

export const JOB_INDUSTRY_HIRE = [
  { value: 'Hire_it', ru: 'IT, интернет, телеком', uz: 'IT, internet, telekom' },
  { value: 'Hire_auto', ru: 'Автомобильный бизнес', uz: 'Avtomobil biznesi' },
  { value: 'Hire_admin', ru: 'Административная работа', uz: "Ma'muriy ish" },
  { value: 'Hire_banks', ru: 'Банки, инвестиции', uz: 'Banklar, investitsiyalar' },
  { value: 'Hire_no_experience', ru: 'Без опыта, студенты', uz: 'Tajribasiz, talabalar' },
  { value: 'Hire_accounting', ru: 'Бухгалтерия, финансы', uz: 'Buxgalteriya, moliya' },
  { value: 'Hire_top_mgmt', ru: 'Высший менеджмент', uz: 'Oliy menejment' },
  { value: 'Hire_gov_nko', ru: 'Госслужба, НКО', uz: 'Davlat xizmati, NNT' },
  { value: 'Hire_household', ru: 'Домашний персонал', uz: 'Uy xodimlari' },
  { value: 'Hire_utilities', ru: 'ЖКХ, эксплуатация', uz: "Kommunal xo'jalik" },
  { value: 'Hire_arts', ru: 'Искусство, развлечения', uz: "San'at, ko'ngilochar" },
  { value: 'Hire_consulting', ru: 'Консультирование', uz: 'Konsalting' },
  { value: 'Hire_courier', ru: 'Курьерская доставка', uz: 'Kuryer yetkazib berish' },
  { value: 'Hire_marketing', ru: 'Маркетинг, реклама, PR', uz: 'Marketing, reklama, PR' },
  { value: 'Hire_medicine', ru: 'Медицина, фармацевтика', uz: 'Tibbiyot, farmatsevtika' },
  { value: 'Hire_education', ru: 'Образование, наука', uz: "Ta'lim, fan" },
  { value: 'Hire_security', ru: 'Охрана, безопасность', uz: "Qo'riqlash, xavfsizlik" },
  { value: 'Hire_sales', ru: 'Продажи', uz: 'Sotuvlar' },
  { value: 'Hire_production', ru: 'Производство, сырьё, с/х', uz: 'Ishlab chiqarish' },
  { value: 'Hire_insurance', ru: 'Страхование', uz: "Sug'urta" },
  { value: 'Hire_construction', ru: 'Строительство', uz: 'Qurilish' },
  { value: 'Hire_taxi', ru: 'Такси', uz: 'Taksi' },
  { value: 'Hire_logistics', ru: 'Транспорт, логистика', uz: 'Transport, logistika' },
  { value: 'Hire_tourism', ru: 'Туризм, рестораны', uz: 'Turizm, restoranlar' },
  { value: 'Hire_hr', ru: 'Управление персоналом', uz: 'Xodimlarni boshqarish' },
  { value: 'Hire_fitness', ru: 'Фитнес, салоны красоты', uz: "Fitnes, go'zallik" },
  { value: 'Hire_legal', ru: 'Юриспруденция', uz: 'Yurisprudensiya' },
]

export const JOB_PRIORITY_OPTIONS = [
  { value: 'ANY', ru: 'Любой', uz: 'Istalgan' },
  { value: 'DAILY_PAY', ru: 'Ежедневные выплаты', uz: 'Har kuni to\'lov' },
  { value: 'UNTIL_17', ru: 'Работа до 17:00', uz: '17:00 gacha ish' },
  { value: 'NO_HEAVY', ru: 'Без тяжестей', uz: "Og'ir yuklarsiz" },
  { value: 'HANDS', ru: 'Работа руками', uz: "Qo'l mehnati" },
  { value: 'START_TOMORROW', ru: 'Приступить завтра', uz: 'Ertaga boshlash' },
]

export const JOB_EMPLOYMENT_OPTIONS = [
  { value: 'FULL', ru: 'Полная', uz: "To'liq" },
  { value: 'PART', ru: 'Частичная', uz: 'Qisman' },
  { value: 'TEMP', ru: 'Временная', uz: 'Vaqtinchalik' },
  { value: 'INTERNSHIP', ru: 'Стажировка', uz: 'Stajirovka' },
]

export const JOB_SCHEDULE_OPTIONS = [
  { value: 'FIXED', ru: 'Фиксированный', uz: 'Qat\'iy' },
  { value: 'FLEX', ru: 'Гибкий', uz: 'Moslashuvchan' },
  { value: 'SHIFT', ru: 'Сменный', uz: 'Smenali' },
  { value: 'FIFO', ru: 'Вахта', uz: 'Vaxta' },
]

export const JOB_FORMAT_OPTIONS = [
  { value: 'ANY', ru: 'Неважно', uz: 'Farqi yo\'q' },
  { value: 'REMOTE', ru: 'Удалённо', uz: 'Masofadan' },
  { value: 'ONSITE', ru: 'В офисе или на объекте', uz: 'Ofis yoki obyektda' },
  { value: 'HYBRID', ru: 'Гибрид', uz: 'Gibrid' },
]

export const JOB_SALARY_PERIOD_OPTIONS = [
  { value: 'ANY', ru: 'Неважно', uz: 'Farqi yo\'q' },
  { value: 'MONTH', ru: 'В месяц', uz: 'Oyiga' },
  { value: 'SHIFT', ru: 'За смену', uz: 'Smenaga' },
  { value: 'WEEK', ru: 'В неделю', uz: 'Haftasiga' },
  { value: 'HOUR', ru: 'За час', uz: 'Soatiga' },
  { value: 'PIECE', ru: 'Сдельно', uz: 'Ishbay' },
]

export const JOB_PAY_FREQUENCY_OPTIONS = [
  { value: 'DAILY', ru: 'Каждый день', uz: 'Har kuni' },
  { value: 'WEEKLY', ru: 'Раз в неделю', uz: 'Haftada bir' },
  { value: 'MONTHLY', ru: 'Раз в месяц', uz: 'Oyda bir' },
  { value: 'TWICE_MONTH', ru: 'Дважды в месяц', uz: 'Oyda ikki' },
  { value: 'THRICE_MONTH', ru: 'Три раза в месяц', uz: 'Oyda uch' },
]

export const JOB_EXPERIENCE_OPTIONS = [
  { value: '', ru: 'Неважно', uz: 'Farqi yo\'q' },
  { value: 'NONE', ru: 'Без опыта', uz: 'Tajribasiz' },
  { value: 'Y1', ru: 'От 1 года', uz: '1 yildan' },
  { value: 'Y3', ru: 'От 3 лет', uz: '3 yildan' },
  { value: 'Y5', ru: 'От 5 лет', uz: '5 yildan' },
]

export const JOB_CITIZENSHIP_OPTIONS = [
  { value: '', ru: 'Неважно', uz: 'Farqi yo\'q' },
  { value: 'UZ', ru: 'Узбекистан', uz: "O'zbekiston" },
  { value: 'ANY', ru: 'Любое', uz: 'Istalgan' },
]

export const JOB_BENEFIT_OPTIONS = [
  { value: 'HOUSING', ru: 'Проживание', uz: 'Yashash joyi' },
  { value: 'INSURANCE', ru: 'Медицинскую страховку', uz: "Tibbiy sug'urta" },
  { value: 'MEALS', ru: 'Питание', uz: 'Ovqatlanish' },
  { value: 'TRAINING', ru: 'Обучение', uz: "O'qitish" },
]

export const JOB_CANDIDATE_OPTIONS = [
  { value: 'AGE_14', ru: 'От 14 лет', uz: '14 yoshdan' },
  { value: 'AGE_16', ru: 'От 16 лет', uz: '16 yoshdan' },
  { value: 'AGE_45', ru: 'Старше 45 лет', uz: '45 yoshdan katta' },
  { value: 'STUDENT', ru: 'Для студентов', uz: 'Talabalar uchun' },
  { value: 'PENSIONER', ru: 'Для пенсионеров', uz: 'Nafaqaxo\'rlar uchun' },
  { value: 'DISABILITY', ru: 'С нарушениями здоровья', uz: "Sog'lig'i cheklangan" },
]

export function jobOptionLabel(opt, lang) {
  if (!opt) return ''
  return lang === 'ru' ? opt.ru : opt.uz
}
